[application]
name = "Rust-Grep"
default_platform = "desktop"

[web.app]
title = "Rust-Grep"

[bundle]
identifier = "com.rust-grep.app"
publisher = "rust-grep"
name = "Rust-Grep"
icon = ["assets/icon.png"]
